config/routes.rb
Iiirc::Application.routes.draw do
  resources :users, except: %w(edit)
  resources :snippets, except: %w(edit update) do
    resources :messages, only: %w(destroy) do
      resources :stars, only: %w(create)
    end
  end
  resources :organizations, only: %w(index show)

  get    '/signin'                  => redirect('/auth/github'), as: :signin
  delete '/signout'                 => 'sessions#destroy',       as: :signout
  get    '/auth/:provider/callback' => 'sessions#callback',      as: :callback
  get    '/signup'                  => 'users#new',              as: :signup
  get    '/transition'              => 'transition#show',        as: :transition
  get    '/image_proxy'             => 'image_proxy#show',       as: :image_proxy
  post   '/snippets/preview'        => 'snippets#preview',       as: :snippet_preview

  scope '/api' do
    resources :snippets, controller: 'api/snippets', only: %w[show]
  end

  root to: 'top#index'
end

app/models/snippet.rb
# coding: utf-8
class Snippet < ActiveRecord::Base
  belongs_to :user
  belongs_to :organization
  has_many   :messages, dependent: :destroy
  has_many   :stars, through: :messages

  attr_writer :content

  scope :date_desc,   -> { order("created_at desc") }
  scope :date_asc,    -> { order("created_at asc")  }
  scope :published,   -> { where(published: true)   }
  scope :unpublished, -> { where(published: false)  }
  scope :with_assoc,  -> { includes(messages: [:stars]) }

  before_create do
    set_default_title
    set_hash_id
  end

  after_create do
    TweetBot.tweet(self) if Rails.env.production? && published?
    PubsubhubbubNotifier.notify if published?
  end

  validates :messages,
    length: { minimum: 1, message: "are blank." }

  def url
    Rails.application.routes.url_helpers.snippet_url(host: "www.iiirc.org", id: id)
  end

  def owner?(user)
    user.try(:id) == user_id
  end

  def latest_star
    stars.max {|s1, s2| s1.updated_at <=> s2.updated_at}
  end

  private
  def set_default_title
    self.title = Time.now.to_s if self.title.blank?
  end

  def set_hash_id
    self.hash_id = Digest::SHA512.hexdigest(Settings.snippet.salt + Time.now.to_i.to_s)[0..19] unless published?
  end
end

app/controllers/api/snippets_controller.rb
class Api::SnippetsController < ApplicationController
  respond_to :json

  def index
    @snippets = Snippet.with_assoc.published.date_desc.page(params[:page]).decorate
    respond_with @snippets
  end

  def show
    @snippet = Snippet.with_assoc.find_by_hash_id(params[:id])
    if @snippet.blank?
      @snippet = Snippet.with_assoc.find_by_id(params[:id])
      return render_not_found unless @snippet.try(:published?)
    end
    @html = render_to_string(partial: 'snippet', layout: false, locals: {snippet: @snippet.decorate, current_user: nil})

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/snippets_controller.rb
# -*- coding: utf-8 -*-
class SnippetsController < ApplicationController
  before_action :set_snippet, only: %w(show destroy)
  before_action :require_sign_in, only: %w(create destroy preview)

  # GET /snippets
  # GET /snippets.json
  # GET /snippets.atom
  def index
    @snippets = Snippet.with_assoc.published.date_desc.page(params[:page]).decorate

    if request.formats.include? :html
      respond_to do |format|
        format.html # index.html.slim
      end
    else
      if stale? @snippets.first
        respond_to do |format|
          format.atom { render atom: @snippets }
          format.json { render json: @snippets }
        end
      end
    end
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
    @snippet = @snippet.decorate

    respond_to do |format|
      format.html # show.html.slim
      format.json { render json: @snippet }
    end
  end

  # GET /snippets/new
  # GET /snippets/new.json
  def new
    @snippet = Snippet.new.decorate

    respond_to do |format|
      format.html # new.html.slim
      format.json { render json: @snippet }
    end
  end

  # POST /snippets
  def create
    content = params[:content].strip
    snippet = current_user.snippets.build(snippet_params)
    snippet.published = params[:commit] == 'public'

    content.each_line do |raw_content|
      snippet.messages.build(raw_content: raw_content.chomp)
    end

    respond_to do |format|
      if snippet.save
        redirect_to = snippet.published? ? snippet : "/snippets/#{snippet.hash_id}"
        format.html { redirect_to redirect_to, notice: 'Snippet was successfully created.' }
      else
        @snippet = snippet.decorate
        format.html { render action: "new" }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Snippet was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def preview
    content = params[:content].strip
    snippet = current_user.snippets.build(snippet_params)
    snippet.messages = content.lines.map {|line| Message.new(snippet: snippet, raw_content: line.chomp)}
    snippet.messages.each &:parse_content
    snippet.published = false
    @snippet = snippet.decorate
    @previewing = true

    respond_to do |format|
      format.html { return render action: :show, layout: false }
    end
  end

  private
  def set_snippet
    @snippet = Snippet.with_assoc.find_by_hash_id(params[:id])

    if @snippet.blank?
      @snippet = Snippet.with_assoc.find_by_id(params[:id])
      return render_not_found unless @snippet.try(:published?)
    end
  end

  def snippet_params
    params.require(:snippet).permit(:title, :organization_id)
  end
end

app/views/snippets/_form.html.slim
= form_for(@snippet) do |f|
  - if @snippet.errors.any?
    .container
      h2
        = pluralize(@snippet.errors.count, "error")
        | &nbsp; prohibited this snippet from being saved:
      ul
        - @snippet.errors.full_messages.each do |msg|
          li= msg
  ul.tabs.container.clear
    li.tab
      input[name="tab" value="paste" type="radio" data-selector="#paste" id="tab-paste" checked]
      label[for="tab-paste"] Paste
    li.tab
      input[name="tab" value="preview" type="radio" data-selector="#preview" id="tab-preview"]
      label[for="tab-preview"] Preview
  #paste.container.active
    = f.text_field :title, class: 'input-text input-text-large', placeholder: 'Title (optional)'
    = text_area_tag :content, @content, id: 'content-textarea', class: 'textarea active', placeholder: '00:00 YourName: Logged in...', required: true
  #preview.container.artice-snippet
    .article-content
      p.loading Loading...
  .container
    - if current_user.present? && current_user.organizations.present?
      .form-org-question.container
        | どの Organization の会話ですか??
      .form-org-radiobox.container
        - current_user.organizations.each do |organization|
          label
            = f.radio_button :organization_id, organization.id
            = organization.login
    .container
      - if current_user.present?
        = button_tag 'Public post!', name: 'commit', value: 'public', type: 'submit', class: 'btn btn-green'
        | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        | #{button_tag 'Secret post!', name: 'commit', value: 'secret', type: 'submit', class: 'btn btn-yellow'}

app/views/snippets/_snippet.html.slim
- nick_nums = {}
- nick_color_count = 12
- nick_num = snippet.nick_offset % nick_color_count
div id="snippet_#{snippet.id}"
  - snippet.messages.each_with_index do |message, index|
    - unless nick_nums[message.nick]
      - nick_nums[message.nick] = nick_num % nick_color_count
      - nick_num += 1
    - line_number = index + 1
    p[class="tweet#{' starred' if message.star_count > 0}" id="L#{line_number}"]
      - if message.time.present?
        - if params[:controller] == "snippets" && params[:action] == "show"
          time= link_to message.time, "#L#{line_number}"
          | &nbsp;
        - else
          time= message.time
          | &nbsp;
        span[class="nick_#{nick_nums[message.nick]}"]
          = message.nick
          | :
        | &nbsp;
        span.message
          = raw message.content
      - else
        = message.raw_content
      - unless @previewing
        span.star
          | &nbsp;
          - if current_user
            = link_to '★', snippet_message_stars_path(snippet, message), method: :post, remote: true
          - else
            = link_to '★', signin_url
          = raw message.star_count_tag
          = raw message.starred_by_tag

app/views/snippets/edit.html.slim
section.section
  = render 'form'
  = form_for(@snippet) do |f|
    | 　  #{link_to 'Destroy', @snippet, method: :delete, data: { confirm: 'Are you sure?' }}

app/views/snippets/index.html.slim
h1 Listing snippets
table
  tr
    th Title
    th Content
    th Published
    th
    th
    th
  - @snippets.each do |snippet|
    tr
      td= snippet.title
      td= render 'snippets/snippet', snippet: snippet
      td= snippet.published
      td= link_to 'Show', snippet
      td= link_to 'Destroy', snippet, method: :delete, data: { confirm: 'Are you sure?' }
br/
= paginate @snippets
= link_to 'New Snippet', new_snippet_path

app/views/snippets/new.html.slim
- if current_user.blank?
  .notice.section
    p
      | u can't create a snippet unless logged in. #{link_to "Sign in with GitHub", "/auth/github", 'data-no-turbolink' => true}
#snippet-form.wrapper
  = render 'form'

app/views/snippets/show.html.slim
- content_for :twitter_card do
  = twitter_card 'summary' do |card|
    - card.title @snippet.title
    - card.description @snippet.twitter_card_description
    - card.site '@iiircorg'
.container.clear
  #content
    - content_for(:title) { @snippet.title }
    article.article.article-snippet
      hgroup.article-header.clear
        h2.title= @snippet.title
        = link_to image_tag(@snippet.user.gravatar_url(size: 48), alt: @snippet.user.username, class: 'user-icon'), user_path(@snippet.user)
      .article-content
        - cache @snippet.cache_key_with_stars format: :html, signed_in: !!current_user do
          = render 'snippet', snippet: @snippet
      - unless @previewing
        .embed_code
          = text_field_tag "embedded_snippet_#{@snippet.published? ? @snippet.id : @snippet.hash_id}", '<script type="text/javascript" src="' + url_for(controller: 'api/snippets', action: 'show', id: (@snippet.published? ? @snippet.id : @snippet.hash_id), format: :js, only_path: false) + '"></script>', readonly: true, class: 'input-text'
        .container
          - if @snippet.owner?(current_user)
            = link_to snippet_path, class: 'btn btn-red', method: :delete, data: { confirm: "Are you sure to delete?" } do
              | Delete Snippet!
        - if @snippet.published?
          .social
            .hatena
              a.hatena-bookmark-button href="http://b.hatena.ne.jp/entry/#{request.url}" data-hatena-bookmark-layout="standard" data-hatena-bookmark-title="#{@snippet.title} - iiirc"
            .twitter
              a.twitter-share-button data-lang="en", data-url="#{request.url}", data-text="#{@snippet.title} - iiirc" href="https://twitter.com/share">ツイート
            .facebook
              .fb-like data-href="#{request.url}" data-layout="button_count" data-send="false" data-show-faces="false"