config/routes.rb
Iiirc::Application.routes.draw do
  resources :users, except: %w(edit)
  resources :snippets, except: %w(edit update) do
    resources :messages, only: %w(destroy) do
      resources :stars, only: %w(create)
    end
  end
  resources :organizations, only: %w(index show)

  get    '/signin'                  => redirect('/auth/github'), as: :signin
  delete '/signout'                 => 'sessions#destroy',       as: :signout
  get    '/auth/:provider/callback' => 'sessions#callback',      as: :callback
  get    '/signup'                  => 'users#new',              as: :signup
  get    '/transition'              => 'transition#show',        as: :transition
  get    '/image_proxy'             => 'image_proxy#show',       as: :image_proxy
  post   '/snippets/preview'        => 'snippets#preview',       as: :snippet_preview

  scope '/api' do
    resources :snippets, controller: 'api/snippets', only: %w[show]
  end

  root to: 'top#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :username

  include Gravtastic
  gravtastic secure: true, size: 24

  has_many :snippets, dependent: :destroy
  has_many :user_organizations, dependent: :destroy
  has_many :organizations, through: :user_organizations
  has_many :stars, dependent: :destroy
  accepts_nested_attributes_for :user_organizations

  def find_or_create_organizations
    octokit_client = Octokit::Client.new(login: username, oauth_token: token)
    return octokit_client.organizations(username).map do |organization|
      Organization.find_or_create_by(login: organization.login, original_id: organization.id)
    end
  end

  def self.new_with_omniauth(auth)
    new do |user|
      user.provider = auth[:provider]
      user.uid      = auth[:uid]
      user.username = auth[:info][:nickname]
      user.email    = auth[:info][:email]
      user.token    = auth[:credentials][:token]
    end
  end

  def self.create_with_omniauth(auth)
    new_with_omniauth(auth).save!
  end
end

app/controllers/users_controller.rb
# coding: utf-8

class UsersController < ApplicationController
  verify session: :params_from_authenticator, only: %w(new create), redirect_to: :root_path, add_flash: { alert: "A unknown error occured.. O_o" }

  # GET /users/iiirc
  def show
    @user = User.find_by_username(params[:id])

    if @user
      snippets = @user.snippets.with_assoc.date_desc.page(params[:page])
      snippets = snippets.published if @user.id != current_user.try(:id) or params[:format] == 'atom'
      @snippets = snippets.decorate
    else
      return render_not_found
    end
  end

  # GET /users
  def new
    @user = User.new_with_omniauth(session[:params_from_authenticator])
    @organizations = @user.find_or_create_organizations
  end

  # POST /users
  def create
    @user = User.new_with_omniauth(session[:params_from_authenticator])
    @organizations = @user.find_or_create_organizations

    # TODO ここでは厳密にこのユーザが本当に Organization に紐づいているかの検証を GitHub 側に確認する必要がある
    @user.attributes = user_params if params[:user].present?

    if @user.save
      session[:user_id] = @user.id
      session.delete(:params_from_authenticator)
      redirect_to root_url, notice: "Signed up!"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(organization_ids: [])
  end
end

app/views/users/new.html.slim
section.wrapper
  .signup_organization.container
    p.form-org-question
      blink
        | あなたが参加している Organization の一覧です。
        br/
        | iiirc では、あなたの投稿と Organization を結びつけることができます。
        br/
        | 結びつけるかどうかは、投稿するときに選ぶことができます。
        br/
        | 結びつけてもいい Organization にチェックを入れてください。
    = form_for @user do |f|
      = render "shared/error_messages", :target => @user
      ul.form-org-radiobox
        - @organizations.each do |org|
          li
            = f.check_box :organization_ids, { :checked => @user.organizations.include?(org), :name => 'user[organization_ids][]' }, org.id, ""
            = f.label org.login
      = f.submit "Sign up!", class: 'btn btn-blue btn-horizontal'

app/views/users/show.html.slim
.container.clear
  #content
    - content_for(:feed_url) { user_url(@user, format: :atom) }
    - content_for(:feed_title) { "#{@user.username}'s recent snippets" }
    article.article.user-profile.clearfix
      h2.user-name= @user.username
      - if @user.organizations.present?
        .organizations
          p
            | Organizations #{@user.username} belongs to
          ul.list.list-disc
            - @user.organizations.each do |organization|
              li= link_to organization.login, organization_path(organization.login)
    - @snippets.each do |snippet|
      article.article.article-snippet
        hgroup.article-header.clear
          h2.title= link_to snippet.title, snippet_path(snippet.published? ? snippet : snippet.hash_id)
        .article-content
          - cache snippet.cache_key_with_stars format: :html, signed_in: !!current_user do
            = render 'snippets/snippet', snippet: snippet
  = paginate @snippets