config/routes.rb
Iiirc::Application.routes.draw do
  resources :users, except: %w(edit)
  resources :snippets, except: %w(edit update) do
    resources :messages, only: %w(destroy) do
      resources :stars, only: %w(create)
    end
  end
  resources :organizations, only: %w(index show)

  get    '/signin'                  => redirect('/auth/github'), as: :signin
  delete '/signout'                 => 'sessions#destroy',       as: :signout
  get    '/auth/:provider/callback' => 'sessions#callback',      as: :callback
  get    '/signup'                  => 'users#new',              as: :signup
  get    '/transition'              => 'transition#show',        as: :transition
  get    '/image_proxy'             => 'image_proxy#show',       as: :image_proxy
  post   '/snippets/preview'        => 'snippets#preview',       as: :snippet_preview

  scope '/api' do
    resources :snippets, controller: 'api/snippets', only: %w[show]
  end

  root to: 'top#index'
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :user_organizations
  has_many :users, through: :user_organizations
  has_many :snippets

  scope :has_snippets, -> { joins(:snippets).uniq }

  def to_param
    login
  end
end

app/controllers/api/organizations_controller.rb
class Api::OrganizationsController < ApplicationController
   respond_to :json

  def index
    @organizations = Organization.has_snippets
    respond_with @organizations
  end
end

app/controllers/organizations_controller.rb
# coding: utf-8

class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.has_snippets

    respond_to do |format|
      format.html # index.html.slim
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/papslimoy-all
  # GET /organizations/papslimoy-all.json
  def show
    @organization  = Organization.find_by_login(params[:id])
    @organizations = Organization.has_snippets
    @snippets      = @organization.snippets.with_assoc.published.date_desc.page(params[:page]).decorate

    respond_to do |format|
      format.html # show.html.slim
      format.json { render json: @organization }
      format.atom { render atom: @snippets }
    end
  end
end

app/views/organizations/index.html.slim
h1 Listing organizations
- @organizations.each do |organization|
  tr
    td= organization.login
    td= link_to 'Show', organization
br/

app/views/organizations/show.html.slim
.container.clear
  nav#navigations
    #organizations.navigation
      h4.title.bubble Organizations
      ul.links
        li.link
          = link_to "#all", root_path
        - @organizations.each do |organization|
          li.link
            = link_to "#" + organization.login, organization
    .navigation
      h4.title.bubble Subscribe
      ul.links
        li.link
          a href="http://twitter.com/iiircorg" target="_blank" Twitter
        li.link
          a href="/snippets.atom" target="_blank" Atom
        li.link
          a href="https://github.com/iiirc/iiirc/" target="_blank" GitHub
  #content
    - content_for(:feed_url) { organization_url(@organization, format: :atom) }
    - content_for(:feed_title) { "#{@organization.login}'s recent snippets" }
    article.article.organization-profile.clearfix
      h2.organization-name= @organization.login
      h3 Members
      - @organization.users.each do |user|
        = link_to image_tag(user.gravatar_url, alt: user.username, class: 'avator'), user_path(user.username)
    - @snippets.each do |snippet|
      article.article.article-snippet
        hgroup.article-header.clear
          h2.title= link_to snippet.title, snippet
          p= link_to image_tag(snippet.user.gravatar_url(size: 48), alt: snippet.user.username, class: 'user-icon'), user_path(snippet.user)
        .article-content
          = render 'snippets/snippet', snippet: snippet
  = paginate @snippets