config/routes.rb
Iiirc::Application.routes.draw do
  resources :users, except: %w(edit)
  resources :snippets, except: %w(edit update) do
    resources :messages, only: %w(destroy) do
      resources :stars, only: %w(create)
    end
  end
  resources :organizations, only: %w(index show)

  get    '/signin'                  => redirect('/auth/github'), as: :signin
  delete '/signout'                 => 'sessions#destroy',       as: :signout
  get    '/auth/:provider/callback' => 'sessions#callback',      as: :callback
  get    '/signup'                  => 'users#new',              as: :signup
  get    '/transition'              => 'transition#show',        as: :transition
  get    '/image_proxy'             => 'image_proxy#show',       as: :image_proxy
  post   '/snippets/preview'        => 'snippets#preview',       as: :snippet_preview

  scope '/api' do
    resources :snippets, controller: 'api/snippets', only: %w[show]
  end

  root to: 'top#index'
end

app/views/layouts/application.html.slim
DOCTYPE html
html
  /! 銀しゃりのまばゆい輝きが、うにやいくらの神々しい光が、鋭利な刃物のように光るサバのにぎりが、IRC クライアントのまっくろなウィンドウを照らしてくれる。
  head
    title= content_for?(:title) ? "#{content_for(:title)} - iiirc" : "iiirc"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = favicon_link_tag "favicon.ico"
    = auto_discovery_link_tag :atom, snippets_url(format: :atom), title: "iiirc's recent snippets"
    - if content_for? :feed_url
      = auto_discovery_link_tag :atom, content_for(:feed_url), title: content_for(:feed_title)
    = twitter_card if content_for?(:twitter_card)
  body[id="page_#{params[:controller]}_#{params[:action]}"]
    header#header.wrapper
      .container.clear
        h1#brand
          = link_to image_tag("iiirc.png", alt: "iiirc") , root_path
        #account_info
          - if current_user
            = link_to image_tag(current_user.gravatar_url(size: 48), alt: current_user.username, class: 'avator'), user_path(current_user.username)
        - if notice
          p#notice= notice
        - if alert
          p#alert= alert
        - if Settings.google_custom_search.try(:cx).present?
          = render 'shared/google_custom_search', cx: Settings.google_custom_search.cx
        .header-right
          - if current_user
            = link_to new_snippet_path, class: 'btn' do
              | + Add New Snippet!
          - else
            = link_to "Sign in with GitHub", "/auth/github", 'data-no-turbolink' => true, class: 'btn btn-blue'
    #contents.wrapper
      = yield
    footer#footer.wrapper.clear
      .container
        p#copyrights iiirc&trade;
        - if current_user
          p#signout
            = current_user.username
            | &nbsp;(#{link_to "Sign out", signout_path, method: :delete})
        - else
          p#powered
            a href="http://sqale.jp/" target="_blank"